# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

    # Configuração da máquina master
    config.vm.define "master" do |master|
      master.vm.box = "ubuntu/focal64"
      master.vm.network "private_network", ip: "192.168.50.10"
      master.vm.provision "shell", inline: <<-SHELL
        apt-get update -y
        apt-get install -y \
          apt-transport-https \
          ca-certificates \
          curl \
          gnupg-agent \
          software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
        add-apt-repository \
           "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
           $(lsb_release -cs) \
           stable"
        apt-get update -y
        apt-get install -y docker-ce docker-ce-cli containerd.io
        usermod -aG docker vagrant
        systemctl enable docker
        # Inicializa o Docker Swarm na master
        docker swarm init --advertise-addr 192.168.50.10
      SHELL
    end

    # Configuração das máquinas nodes
    nodes = ["node01", "node02", "node03"]
    nodes.each_with_index do |node, index|
      config.vm.define node do |n|
        n.vm.box = "ubuntu/focal64"
        n.vm.network "private_network", ip: "192.168.50.#{11 + index}"
        n.vm.provision "shell", inline: <<-SHELL
          apt-get update -y
          apt-get install -y \
            apt-transport-https \
            ca-certificates \
            curl \
            gnupg-agent \
            software-properties-common
          curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
          add-apt-repository \
             "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
             $(lsb_release -cs) \
             stable"
          apt-get update -y
          apt-get install -y docker-ce docker-ce-cli containerd.io
          usermod -aG docker vagrant
          systemctl enable docker
          # Captura o token de worker da master e junta ao swarm
          TOKEN=$(vagrant ssh master -c "docker swarm join-token worker -q")
          docker swarm join --token $TOKEN 192.168.50.10:2377
        SHELL
      end
    end
  end